name: Update Dashboard

on: 
  push:
    branches: [main, master]
  #schedule:  
  #  - cron: '0 15,18,21 * * 1-5'

jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-latest 
    #permissions:
    #  contents: write
    #  actions: write
    #  pages: write
    container: 
      image: mgaloto/bs4dashdolar:01
    steps:
    - name: checkout_repo
      uses: actions/checkout@v3
      with: 
        ref: 'main'
    - name: Deploy app
      run: Rscript R/deploy.R
      env:
        SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
        TOKEN: ${{ secrets.TOKEN }}
        SECRET: ${{ secrets.SECRET }}

